#include "plane.hpp"
#include <cassert>

void test01() {
  Plane plane;
  std::stringstream input, output, true_output;
  input << "FIRST_CLASS_SEGMENT 400" << std::endl;
  input << "BUSINESS_CLASS_SEGMENT 800" << std::endl;
  input << "ECONOMY_CLASS_SEGMENT 1000" << std::endl;
  input << "PILOT 0 0" << std::endl;
  input << "FLIGHT_ATTENDANT 0 0" << std::endl;
  input << "ECONOMY 5 20" << std::endl;
  input << "ECONOMY 5 4" << std::endl;
  input << "ECONOMY 5 10" << std::endl;
  input << "ECONOMY 5 15" << std::endl;
  input << "ECONOMY 5 16" << std::endl;
  input << "ECONOMY 5 10" << std::endl;
  input << "ECONOMY 5 20" << std::endl;
  input << "ECONOMY 5 21" << std::endl;
  input << "ECONOMY 5 20" << std::endl;
  input << "ECONOMY 5 15" << std::endl;
  input << "ECONOMY 5 6" << std::endl;
  input << "ECONOMY 5 8" << std::endl;
  input << "ECONOMY 5 10" << std::endl;
  input << "BUSINESS 0 10 34" << std::endl;
  input << "FIRST_CLASS 30 30 200 200" << std::endl;
  input << "FIRST_CLASS 0 0 850 100" << std::endl;
  plane.load(input, output);
  true_output << "!!PASSENGER’S LUGGAGE REMOVED FROM FLIGHT, ID = 12!!"
              << std::endl;
  true_output << "!!PASSENGER’S LUGGAGE REMOVED FROM FLIGHT, ID = 6!!"
              << std::endl;
  true_output << "!!PASSENGER’S LUGGAGE REMOVED FROM FLIGHT, ID = 11!!"
              << std::endl;
  true_output << "!!PASSENGER’S LUGGAGE REMOVED FROM FLIGHT, ID = 9!!"
              << std::endl;
  true_output << "!!PASSENGER’S LUGGAGE REMOVED FROM FLIGHT, ID = 3!!"
              << std::endl;
  true_output << "!!PASSENGER’S LUGGAGE REMOVED FROM FLIGHT, ID = 10!!"
              << std::endl;
  true_output << "!!PASSENGER’S LUGGAGE REMOVED FROM FLIGHT, ID = 7!!"
              << std::endl;
  assert(output.str() == true_output.str());
}

void test02() {
  Plane plane;
  std::stringstream input, output, true_output;
  input << "FIRST_CLASS_SEGMENT 400" << std::endl;
  input << "BUSINESS_CLASS_SEGMENT 800" << std::endl;
  input << "ECONOMY_CLASS_SEGMENT 1000" << std::endl;
  input << "PILOT 0 0" << std::endl;
  input << "PILOT 0 0" << std::endl;
  input << "FLIGHT_ATTENDANT 0 0" << std::endl;
  input << "FLIGHT_ATTENDANT 0 0" << std::endl;
  input << "FLIGHT_ATTENDANT 0 0" << std::endl;
  input << "FLIGHT_ATTENDANT 0 0" << std::endl;
  input << "FLIGHT_ATTENDANT 0 0" << std::endl;
  input << "FLIGHT_ATTENDANT 0 0" << std::endl;
  input << "BUSINESS 0 0 0 0" << std::endl;
  input << "BUSINESS 0 0 0 0" << std::endl;
  input << "BUSINESS 0 0 0 0" << std::endl;
  input << "BUSINESS 0 0 0 0" << std::endl;
  input << "BUSINESS 0 0 0 0" << std::endl;
  input << "BUSINESS 0 0 0 0" << std::endl;
  input << "BUSINESS 0 0 0 0" << std::endl;
  input << "BUSINESS 0 0 0 0" << std::endl;
  input << "BUSINESS 0 0 0 0" << std::endl;
  input << "BUSINESS 0 0 0 0" << std::endl;
  input << "BUSINESS 0 0 0 0" << std::endl;
  input << "FIRST_CLASS 0 0 0 0" << std::endl;
  input << "FIRST_CLASS 0 0 0 0" << std::endl;
  input << "FIRST_CLASS 0 0 0 0" << std::endl;
  input << "FIRST_CLASS 0 0 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  input << "ECONOMY 0 0" << std::endl;
  plane.load(input, output);
  assert(output.str() == "!!CANT REGISTER ECONOMY PASSENGER, ID = 223!!\n");
}

void test03() {
  Plane plane;
  std::stringstream input, output, true_output;
  input << "FIRST_CLASS_SEGMENT 400" << std::endl;
  input << "BUSINESS_CLASS_SEGMENT 800" << std::endl;
  input << "ECONOMY_CLASS_SEGMENT 1000" << std::endl;
  input << "PILOT 10 0" << std::endl;
  input << "PILOT 0 20" << std::endl;
  input << "ECONOMY 100 20" << std::endl;
  plane.load(input, output);
  true_output << "!!CANT REGISTER PILOT PASSENGER, ID = 1!!" << std::endl;
  true_output << "!!CANT REGISTER PILOT PASSENGER, ID = 2!!" << std::endl;
  true_output << "!!CANT REGISTER ECONOMY PASSENGER, ID = 3!!" << std::endl;
  assert(output.str() == true_output.str());
}

void test() {
  test01();
  test02();
  test03();
}

int main() {
  test();
  return 0;
}
